title: Lily's GitHub Pages
author: lily1109
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Learn about what GitHub Pages is and how to use it to create a wonderful site for you.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
